import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

const poppings = Poppins({
    weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
    subsets: ["latin", "latin-ext", "devanagari"],
});

export const metadata: Metadata = {
    title: "KTU Mailer",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={`${poppings.className} h-screen w-screen flex flex-col items-center justify-center`}
            >
                {children}
            </body>
        </html>
    );
}
